apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mobility-api-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "connected-car-frontend-svc,connected-car-query-svc"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /ws/vehicles
            pathType: Prefix
            backend:
              service:
                name: connected-car-frontend-svc
                port:
                  number: 80
          - path: /api/map/
            pathType: Prefix
            backend:
              service:
                name: connected-car-frontend-svc
                port:
                  number: 80
          - path: /api/telemetry
            pathType: Prefix
            backend:
              service:
                name: connected-car-command-svc
                port:
                  number: 80
          - path: /api/vehicles
            pathType: Prefix
            backend:
              service:
                name: connected-car-query-svc
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: connected-car-query-svc
                port:
                  number: 80
          - path: /api/health
            pathType: Prefix
            backend:
              service:
                name: connected-car-query-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: connected-car-frontend-svc
                port:
                  number: 80
